### ISSUE TITLE
No usable version on npmjs for released Assemble

### ISSUE THREAD

**Issue by evil-shrike** [assemble/grunt-assemble-lunr#5]
Hi.
I found that the only published version of this plugin is 0.2.1 which (as stated in README) is for unreleased version of Assemble (0.5.0/0.6.0). The last released version of Assemble is 0.4.0 and there's no any version of the plugin on npnjs.org for that version. 
Can you please publish 0.1.0 version?

**Comment by doowb** [comment]
Just renamed this to `grunt-assemble-lunr` and published for the `grunt-assemble / assemble 0.4.x` version of assemble.
